@apiUrl = http://localhost:8080
@cupId = xxxxxxxxxxxxxxxxxxxxxxxxx 


### Home
GET {{apiUrl}}


### Movies

### Fetch all movies
GET {{apiUrl}}/movies


### Cups

### Run a cup
POST {{apiUrl}}/cups
Content-Type: application/json

[
    {
        "id": "4",
        "title": "Title4",
        "year": 2017,
        "rating": 7.8
    },
    {
        "id": "6",
        "title": "Title6",
        "year": 2020,
        "rating": 9.7
    },
    {
        "id": "3",
        "title": "Title3",
        "year": 2018,
        "rating": 8.2
    },
    {
        "id": "8",
        "title": "Title8",
        "year": 2020,
        "rating": 8.9
    },
    {
        "id": "2",
        "title": "Title2",
        "year": 2019,
        "rating": 8.2
    },
    {
        "id": "1",
        "title": "Title1",
        "year": 2018,
        "rating": 7.8
    },
    {
        "id": "7",
        "title": "Title7",
        "year": 2017,
        "rating": 8.8
    },
    {
        "id": "5",
        "title": "Title5",
        "year": 2019,
        "rating": 9.5
    }
]

### Fetch all cups
GET {{apiUrl}}/cups

### Fetch cup
GET {{apiUrl}}/cups/{{cupId}}
