@apiUrl = http://localhost:8080
@cupId = xxxxxxxxxxxxxxxxxxxxxxxxx 


### Home
GET {{apiUrl}}


### Movies

### Fetch all movies
GET {{apiUrl}}/movies


### Cups

### Run a cup
POST {{apiUrl}}/cups
Content-Type: application/json

["4", "6", "3", "8", "2", "1", "7", "5"]

### Fetch all cups
GET {{apiUrl}}/cups

### Fetch cup
GET {{apiUrl}}/cups/{{cupId}}
